### PR TITLE
Fixes for new dependencies

### PR DESCRIPTION
**Pull request by 3noch**
These are necessary for newer nixpkgs used by obelisk.

### CODE REVIEW

**Comment by ali-abrar** [comment]
I think it might be better not to make whitespace/formatting changes since they'll only make it more difficult to merge upstream back into this repo.

**Review by ali-abrar — CHANGES_REQUESTED** [review]
Remove whitespace commit

**Comment by 3noch** [comment]
Sure.

**Comment by 3noch** [comment]
@ali-abrar I rebased the commit away.

**Pull request merged**
