### PR TITLE
add instance for `PersistBackend (ExceptT m)` just like `MaybeT`

### PR DESCRIPTION
**Pull request by danbornside**

### CODE REVIEW

**Comment by 3noch** [comment]
Does `throwError` in `ExceptT` cause a rollback?

**Comment by 3noch** [comment]
I'm guessing it does not. But would this be a source of confusion?

**Comment by ryantrinkle** [comment]
@3noch That would depend on whether the exception bubbles up to runDb, which it can't because runDb doesn't run `runExceptT` or anything like that.  There *is* the issue that changes made prior to a `throwError` would still occur, which is the same as ExceptT for IO, so it seems reasonable to me.  @danbornside anything we can do to be defensive about that?

**Comment by 3noch** [comment]
Yes as long as you're forced to `runExcepT` inside `runDb` it seems like it wouldn't be confusing. The types would force you to choose how `throwError` propagates.

**Comment by ryantrinkle** [comment]
Well, the other thing it *could* do would be to use subtransactions and roll *those* back when something throws.

**Comment by 3noch** [comment]
True...although my gut says that should be a separate monad (or perhaps the same DB monad but with some sort of nesting semantics added).

**Comment by 3noch** [comment]
I suddenly want this. Can we merge it?

**Comment by Ericson2314** [comment]
@xplat's thing might be in conflict?

**Comment by 3noch** [comment]
@Ericson2314 which thing?

**Comment by Ericson2314** [comment]
https://github.com/obsidiansystems/rhyolite/pull/57/files . I forget that was to rhyolite not groundhog, but they still seem opposed.

**Comment by 3noch** [comment]
Oh, that PR prevents you from using `runDb` inside of `ExceptT` but this PR lets you run `ExceptT` inside `runDb`. Put together they are *swapping* where `ExceptT` is allowed in exactly the right way.

**Comment by Ericson2314** [comment]
@3noch Oh, by bad. Nice!

**Pull request merged**
