### PR TITLE
Add support for 'numeric' PG type

### PR DESCRIPTION
**Pull request by 3noch**
PostgreSQL's `numeric` type is an "infinite" precision floating point number. It's analogue in Haskell is `Scientific` (used by aeson, cassava, and postgresql-simple for this purpose). I did not pin the version for scientific because it's not pinned by postgresql-simple either. This, of course, introduces an orphan instance. Please provide feedback.

### CODE REVIEW

**Comment by 3noch** [comment]
Providing the precision and scale explicitly could be supported like this:

```haskell
-- | Type representing PostgreSQL's @numeric@ column type, parameterized at the type level by two 'Nat's.
newtype PgNumeric (precision :: Nat) (scale :: Nat) = PgNumeric { unPgNumeric :: Scientific }

instance (KnownNat precision, KnownNat scale) => PersistField (PgNumeric precision scale) where
  persistName _ = "PgNumeric(" <> show (natVal $ Proxy @precision) <> "," <> show (natVal $ Proxy @scale) <> ")"
  toPersistValues = primToPersistValue
  fromPersistValues = primFromPersistValue
  dbType _ _ = DbTypePrimitive
    (DbOther (OtherTypeDef [Left $ "numeric(" <> show (natVal $ Proxy @precision) <> "," <> show (natVal $ Proxy @scale) <> ")"]))
    True
    Nothing
    Nothing

instance (KnownNat precision, KnownNat scale) => PrimitivePersistField (PgNumeric precision scale) where
  toPrimitivePersistValue  _ (PgNumeric c) = PersistCustom
    (Utf8 $ fromString $ show c <> "::numeric(" <> show (natVal $ Proxy @precision) <> "," <> show (natVal $ Proxy @scale) <> ")")
    []
  fromPrimitivePersistValue _ (PersistCustom pv _) = case readMaybe (T.unpack $ T.decodeUtf8 $ fromUtf8 pv) of
    Nothing -> error $ "fromPrimitivePersistValue: Could not parse PgNumeric: " ++ show pv
    Just v -> PgNumeric v
  fromPrimitivePersistValue _ (PersistInt64 v) = PgNumeric $ fromIntegral v
  fromPrimitivePersistValue _ (PersistDouble v) = PgNumeric $ Sci.fromFloatDigits v
  fromPrimitivePersistValue _ pv = error $ "fromPrimitivePersistValue: Unexpected PersistValue when trying to parse PgNumeric: nn" ++ show pv

instance NeverNull (PgNumeric precision scale)
```

**Comment by ryantrinkle** [comment]
Merging, but should we follow up on any of your other comments here?

**Comment by 3noch** [comment]
I could add a PR for the specified precision version if you felt it was helpful. Since we didn't support `numeric` before at all, I wasn't sure if adding even more specific support was useful.

**Comment by ryantrinkle** [comment]
Right; let's add that when we have a use for it.  Regarding the orphan: is there anywhere we could move the instance where it wouldn't be an orphan?

**Comment by 3noch** [comment]
Two ways I can think of: Make some generic "infinite precision floating point number" part of Groundhog's primitive type. This would move the instance into groundhog proper. And of course the other is to add a `newtype` like `PgNumeric` but without the precision specified.

**Comment by 3noch** [comment]
There's also something interesting going on here: https://github.com/obsidiansystems/groundhog/blob/fd023ea6d938d769bbe138a0cca220d5a6a3ec73/groundhog-postgresql/Database/Groundhog/Postgresql.hs#L793-L807

I'm not sure how to leverage it since it explicitly does not support non-primitive types.

**Pull request merged**
